apiVersion: config.adrp.xyz/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: config/v1alpha1/user
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    email: john@smith.com
    fullName: John Smith
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    username: john
